// <auto-generated />
namespace HxJumper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_remarkmessge_testresult_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_remarkmessge_testresult_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201501121524001_add_remarkmessge_testresult_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
